config/routes.rb
PMS::Application.routes.draw do
  resources :specializations

  resources :resources

  resources :clients

  resources :projects
  get "welcome/index"

  root 'welcome#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/project.rb
class Project < ActiveRecord::Base
  validates :projectname, presence: true, length: {minimum: 2}
  validates :teamleader, presence: true, length: {minimum: 2}

end

app/models/resource.rb
class Resource < ActiveRecord::Base
end

app/models/specialization.rb
class Specialization < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render action: 'show', status: :created, location: @client }
      else
        format.html { render action: 'new' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url}
      format.json { head :no_content }
    end
  end

 
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
      params.require(:client).permit(:name, :country, :address, :mobilenumber, :email)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
   
  def new
    @project =Project.new
  end
  
    def create
     @project = Project.new(project_params)
     
     if @project.save
      redirect_to @project, notice: 'Project added successfully'
     else
         render 'new'
      end
    end
    
    def index
      @projects = Project.all
    end
  
   def edit
      @project = Project.find(params[:id])
    
   end
   
     def update
      @project = Project.find(params[:id])
      if @project.update_attributes(params[:prject])
         redirect_to :action => 'show', :id => @project
      else
         render :action => 'edit'
      end
   end
   
  def show
    @project = Project.find(params[:id])
  end
  
    def destroy
    @project = Project.find(params[:id])
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was deleted successfully'}
      format.json { head :no_content }
    end
  end
  
  private
    def project_params
      params.require(:project).permit(:projectname, :teamleader, :clientname)
    end
end

app/controllers/resources_controller.rb
class ResourcesController < ApplicationController
  before_action :set_resource, only: [:show, :edit, :update, :destroy]

  # GET /resources
  # GET /resources.json
  def index
    @resources = Resource.all
  end

  # GET /resources/1
  # GET /resources/1.json
  def show
  end

  # GET /resources/new
  def new
    @resource = Resource.new
  end

  # GET /resources/1/edit
  def edit
  end

  # POST /resources
  # POST /resources.json
  def create
    @resource = Resource.new(resource_params)

    respond_to do |format|
      if @resource.save
        format.html { redirect_to @resource, notice: 'Resource was successfully created.' }
        format.json { render action: 'show', status: :created, location: @resource }
      else
        format.html { render action: 'new' }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /resources/1
  # PATCH/PUT /resources/1.json
  def update
    respond_to do |format|
      if @resource.update(resource_params)
        format.html { redirect_to @resource, notice: 'Resource was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @resource.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /resources/1
  # DELETE /resources/1.json
  def destroy
    @resource.destroy
    respond_to do |format|
      format.html { redirect_to resources_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_resource
      @resource = Resource.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def resource_params
      params.require(:resource).permit(:fname, :lname, :dob, :phnumber, :email, :expr, :spclizn)
    end
end

app/controllers/specializations_controller.rb
class SpecializationsController < ApplicationController
  before_action :set_specialization, only: [:show, :edit, :update, :destroy]

  # GET /specializations
  # GET /specializations.json
  def index
    @specializations = Specialization.all
  end

  # GET /specializations/1
  # GET /specializations/1.json
  def show
  end

  # GET /specializations/new
  def new
    @specialization = Specialization.new
  end

  # GET /specializations/1/edit
  def edit
  end

  # POST /specializations
  # POST /specializations.json
  def create
    @specialization = Specialization.new(specialization_params)

    respond_to do |format|
      if @specialization.save
        format.html { redirect_to @specialization, notice: 'Specialization was successfully created.' }
        format.json { render action: 'show', status: :created, location: @specialization }
      else
        format.html { render action: 'new' }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /specializations/1
  # PATCH/PUT /specializations/1.json
  def update
    respond_to do |format|
      if @specialization.update(specialization_params)
        format.html { redirect_to @specialization, notice: 'Specialization was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @specialization.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /specializations/1
  # DELETE /specializations/1.json
  def destroy
    @specialization.destroy
    respond_to do |format|
      format.html { redirect_to specializations_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_specialization
      @specialization = Specialization.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def specialization_params
      params.require(:specialization).permit(:name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    @projects = Project.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/resources_helper.rb
module ResourcesHelper
end

app/helpers/specializations_helper.rb
module SpecializationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
<% if @client.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

	<ul>
		<% @client.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="row">
	<div class='large-6'>
		<div class="row collapse">
			<div class='large-4 columns'>
				<%= f.label :name %>
			</div>
			<div class="large-6 columns">
				<%= f.text_field :name %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns">
				<%= f.label :country %>
			</div>
			<div class="large-6 columns">
				<%= f.text_field :country %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns">
				<%= f.label :address %>
			</div>

			<div class="large-6 columns">
				<%= f.text_area :address %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns">
				<%= f.label :mobilenumber %>
			</div>
			<div class="large-6 columns">
				<%= f.telephone_field :mobilenumber %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns">
				<%= f.label :email %>
			</div>
			<div class="large-6 columns">
				<%= f.email_field :email %>
			</div>
		</div>
		<br />
		<div class="row">
			<div class="large-4 large-offset-4 columns">
				<%= f.submit 'Submit', :class =>'tiny button radius' %>
			</div>
		</div>

		<% end %>
	</div>
</div>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<div class="row collapse">
	<h2>Listing clients</h2>

	<table class="large-12">
		<thead>
			<tr>
				<th>Name</th>
				<th>Country</th>
				<th>Address</th>
				<th>Mobilenumber</th>
				<th>Email</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @clients.each do |client| %>
			<tr>
				<td><%= client.name %></td>
				<td><%= client.country %></td>
				<td><%= client.address %></td>
				<td><%= client.mobilenumber %></td>
				<td><%= client.email %></td>
				<td><%= link_to 'Show', client %></td>
				<td><%= link_to 'Edit', edit_client_path(client) %></td>
				<td><%= link_to 'Delete', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>
	<div class="row collapse">
		<%= link_to 'New Client', new_client_path %>
	</div>
</div>

app/views/clients/new.html.erb
<div class="row collapse">
	<h1>New client</h1></div>

	<%= render 'form' %>
	
	<%= link_to 'Back', clients_path %>
		

app/views/clients/show.html.erb
<p id="notice" style="padding-top: 30px"><%= notice %></p>

<h2 class="subheader">Client Details</h2>
<p>
  <strong>Name:</strong>
  <%= @client.name %>
</p>

<p>
  <strong>Country:</strong>
  <%= @client.country %>
</p>

<p>
  <strong>Address:</strong>
  <%= @client.address %>
</p>

<p>
  <strong>Mobilenumber:</strong>
  <%= @client.mobilenumber %>
</p>

<p>
  <strong>Email:</strong>
  <%= @client.email %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Zurb Foundation %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div data-alert class="alert-box round <%= name.to_s == 'notice' ? 'success' : 'alert' %>">
      <%= content_tag :div, msg %>
      <a href="#" class="close">&times;</a>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Zurb Foundation 5 %>
<nav class="top-bar" data-topbar>
  <ul class="title-area">
    <li class="name"><h1><%= link_to 'Project Management System', root_path %></h1></li>
    <li class="toggle-topbar menu-icon"><a href="#">Menu</a></li>
  </ul>
  <div class="top-bar-section right">
    <ul>
      <%= render 'layouts/navigation_links' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

<li class = "has-dropdown"><%= link_to 'Projects', projects_url %>
	<ul class="dropdown">
		<li><%= link_to 'Add Project', new_project_url %></li>
		<li><%= link_to 'View Projects', projects_url %></li>
	</ul>
</li>
<li class = "has-dropdown"><%= link_to 'Clients', clients_url %>
	<ul class="dropdown">
		<li><%= link_to 'Add Client', new_client_url %></li>
		<li><%= link_to 'View Clients', clients_url %></li>
	</ul>
</li>
<li class = "has-dropdown"><%= link_to 'Resources', resources_url %>
	<ul class="dropdown">
		<li><%= link_to 'Add Resource', new_resource_url %></li>
		<li><%= link_to 'View Resources', resources_url %></li>
	</ul>
</li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title><%= content_for?(:title) ? yield(:title) : "Pms" %></title>
		<meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pms" %>">
		<%= stylesheet_link_tag 'application', media: 'all'%>
		<%# Modernizr is required for Zurb Foundation %>
		<%= javascript_include_tag 'vendor/modernizr' %>
		<%= javascript_include_tag 'application' %>
		<%= csrf_meta_tags %>
		<%= stylesheet_link_tag 'datepicker', media: 'all' %>
		<%= stylesheet_link_tag 'zurb5-multiselect', media: 'all' %>
		<%= javascript_include_tag 'datepicker' %>
		<%= javascript_include_tag 'zurb5-multiselect' %>

		<!-- <%= stylesheet_link_tag '//code.jquery.com/ui/1.11.0/themes/smoothness/jquery-ui.css', media: 'all'%>
		<%= javascript_include_tag '//code.jquery.com/jquery-1.10.2.js' %>
		<%= javascript_include_tag '//code.jquery.com/ui/1.11.0/jquery-ui.js'%>
		<%= stylesheet_link_tag '/resources/demos/style.css', media: 'all' %>

		<script>
		$(function() {
		$( "#datepicker" ).datepicker({
		changeMonth: true,
		changeYear: true,
		maxdate: "0",
		yearRange: '-100:+0'
		});
		});
		</script> -->

		<script>
			$('.fdatepicker').DatePicker();
			$("#multiselect").zmultiselect({filter:false});
		</script>

	</head>
	<body>
		<header>
			<%= render 'layouts/navigation' %>
		</header>
		<main role="main">
			<%= render 'layouts/messages' %>
			<%= yield %>
		</main>
	</body>
</html>

app/views/projects/edit.html.erb
<div class="row collapse" style="padding-top: 30px">
	<h1>Edit Project</h1>
</div>


<%= form_for :project, url: projects_path do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@project.errors.count, "error")%> prohibited this project from being saved:</h2>
	<ul class='error'>
		<% @project.errors.full_messages.each do |msg|%>
		<li class='error'>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="row collapse">
	<div class="large-4 columns">
		<%= f.label :project_name, class: 'right-inline'  %>
	</div>
	<div class="large-6 columns">
		<%= f.text_field :projectname %>
	</div>
</div>

<div class="row collapse">
	<div class="large-4 columns">
		<%= f.label :teamleader, class: 'right-inline'  %>
	</div>
	<div class="large-6 columns">
		<%= f.text_field :teamleader %>
	</div>
</div>

<div class="row collapse">
	<div class="large-4 columns">
		<%= f.label :client, class: 'right-inline'  %>
	</div>
	<div class="large-6 columns" class='button dropdown'>
		<%= f.select :client, [['UEMS',1], ['NGV',2], ['iClick',3]] , {:include_blank => 'Select'}  %>
	</div>
</div>
<br />

<div class="row collapse">
	<div class="large-4 columns"></div>
		<div class="large-6 columns"><%= f.submit 'Submit', :class=> 'small button round' %>
		<%= link_to 'Back', projects_path,:class=>"small button round" %></div>
	</div>
</div>

<%end%>

app/views/projects/index.html.erb
<div class="row collapse">
	<h1>Listing Projects</h1>

	<table class="large-12">
		<thead>
			<tr>
				<th>Project Name</th>
				<th>Teamleader</th>
				<th>Client</th>
				<th colspan="3"></th>
			</tr>
		</thead>

		<% @projects.each do |project| %>
		<tbody>
			<tr>
				<td class="description"><%= project.projectname %></td>
				<td class="description"><%= project.teamleader %></td>
				<td class="description"><%= project.client %></td>
				<td class="cta-button"><%= link_to 'Show', project_path(project) %></td>
				<td class="cta-button"><%= link_to 'Edit', edit_project_path(project) %></td>
				<td class="cta-button"><%= link_to 'Delete', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
		</tbody>
		<% end %>
	</table>
	<br />
	<div class="row collapse">
		<%= link_to 'New Project', new_project_path %>
	</div>
</div>

app/views/projects/new.html.erb
<div class="row collapse">
	<h1>New Project</h1>
</div>

<%= form_for :project, url: projects_path do |f| %>
<% if @project.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@project.errors.count, "error")%> prohibited this project from being saved:</h2>
	<ul class='error'>
		<% @project.errors.full_messages.each do |msg|%>
		<li class='error'>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="row">
	<div class='large-5'>
		<div class="row collapse">
			<div class="large-4 columns">
				<%= f.label :project_name, class: 'right-inline'  %>
			</div>
			<div class="large-6 columns">
				<%= f.text_field :projectname %>
			</div>
		</div>

		<div class="row collapse">
			<div class="large-3 columns">
				<%= f.label :teamleader, class: 'right-inline'  %>
			</div>
			<div class="large-6 columns">
				<%= f.text_field :teamleader %>
			</div>
		</div>

		<div class="row collapse">
			<div class="large-3 columns">
				<%= f.label :client, class: 'right-inline'  %>
			</div>
			<div class="large-6 columns" class='dropdown'>
				<%= f.select :client, [['UEMS',1], ['NGV',2], ['iClick',3]] , {:include_blank => 'Select'}%>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 large-offset-8 columns">
				<%= f.submit 'Submit', class: 'tiny button radius' %>
			</div>
		</div>
	</div>
</div>

<%end%>
<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p>
	<strong>Project Name:</strong>
	<%= @project.projectname %>
</p>

<p>
	<strong>Teamleader:</strong>
	<%= @project.teamleader %>
</p>

<p>
	<strong>Client:</strong>
	<%= @project.client %>
</p>

<%= link_to 'Back', projects_path,  :class=>"has-tip" %>

app/views/resources/_form.html.erb
<%= form_for(@resource) do |f| %>
<% if @resource.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@resource.errors.count, "error") %> prohibited this resource from being saved:</h2>

	<ul>
		<% @resource.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="row">
	<div class='large-6'>
		<div class="row collapse">
			<div class="large-4 columns right-inline">
				<%= f.label :first_name %>
			</div>
			<div class="large-6 columns">
				<%= f.text_field :fname %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns right-inline">
				<%= f.label :last_name %>
			</div>
			<div class="large-6 columns">
				<%= f.text_field :lname %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns right-inline">
				<%= f.label :date_of_birth %>
			</div>
			<div class="large-6 columns">
				<%= f.date_field :dob,  :class => 'fdatepicker' %>

			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns right-inline">
				<%= f.label :phonenumber %>
			</div>
			<div class="large-6 columns">
				<%= f.phone_field :phnumber %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns right-inline">
				<%= f.label :email %>
			</div>
			<div class="large-6 columns">
				<%= f.text_field :email %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns right-inline">
				<%= f.label :experience %>
			</div>
			<div class="large-6 columns">
				<%= f.number_field :expr %>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 columns right-inline">
				<%= f.label :specialization %>
			</div>
			<div class="large-6 columns">
				<%= f.select :spclizn, [['asp.net',1], ['c#',2], ['sql',3]], {:include_blank => 'Select'}, :multiple => true, :id => 'multiselect'%>
			</div>
		</div>
		<div class="row collapse">
			<div class="large-4 large-offset-4 columns">
				<%= f.submit 'Submit', class: 'small button radius' %>
			</div>
		</div>
		<% end %>
	</div>
</div>

app/views/resources/edit.html.erb
<h1>Editing resource</h1>

<%= render 'form' %>

<%= link_to 'Show', @resource %> |
<%= link_to 'Back', resources_path %>

app/views/resources/index.html.erb
<div class="row">
<h1>Listing resources</h1>

<table class="large-12">
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Dob</th>
      <th>Phonenumber</th>
      <th>Email</th>
      <th>Experience</th>
      <th>Sepcialization</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @resources.each do |resource| %>
      <tr>
        <td><%= resource.fname %></td>
        <td><%= resource.lname %></td>
        <td><%= resource.dob %></td>
        <td><%= resource.phnumber %></td>
        <td><%= resource.email %></td>
        <td><%= resource.expr %></td>
        <td><%= resource.spclizn %></td>
        <td><%= link_to 'Show', resource %></td>
        <td><%= link_to 'Edit', edit_resource_path(resource) %></td>
        <td><%= link_to 'Destroy', resource, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Resource', new_resource_path %>
</div>

app/views/resources/new.html.erb
<div class="row collapse" >
<h1>New resource</h1>
</div>
<%= render 'form' %>

<%= link_to 'Back', resources_path %>

app/views/resources/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Fname:</strong>
  <%= @resource.fname %>
</p>

<p>
  <strong>Lname:</strong>
  <%= @resource.lname %>
</p>

<p>
  <strong>Dob:</strong>
  <%= @resource.dob %>
</p>

<p>
  <strong>Phnumber:</strong>
  <%= @resource.phnumber %>
</p>

<p>
  <strong>Email:</strong>
  <%= @resource.email %>
</p>

<p>
  <strong>Expr:</strong>
  <%= @resource.expr %>
</p>

<p>
  <strong>Spclizn:</strong>
  <%= @resource.spclizn %>
</p>

<%= link_to 'Edit', edit_resource_path(@resource) %> |
<%= link_to 'Back', resources_path %>

app/views/specializations/_form.html.erb
<%= form_for(@specialization) do |f| %>
<% if @specialization.errors.any? %>
<div id="error_explanation">
	<h2><%= pluralize(@specialization.errors.count, "error") %> prohibited this specialization from being saved:</h2>

	<ul>
		<% @specialization.errors.full_messages.each do |msg| %>
		<li>
			<%= msg %>
		</li>
		<% end %>
	</ul>
</div>
<% end %>

<div class="large-4">
	<div class="row collapse">
		<div class="large-4 columns right-inline">
			<%= f.label :name %>
		</div>
		<div class="large-8 columns">
			<%= f.text_field :name %>
		</div>
	</div>
	<div class="row collapse">
		<div class="large-4 large-offset-4 columns">
			<%= f.submit 'Submit', :class => 'tiny button radius'%>
		</div>
	</div>
	</div>
	<% end %>

app/views/specializations/edit.html.erb
<h1>Editing specialization</h1>

<%= render 'form' %>

<%= link_to 'Show', @specialization %> |
<%= link_to 'Back', specializations_path %>

app/views/specializations/index.html.erb
<div class="row collapse">
	<h1>Listing specializations</h1>

	<table class="large-12">
		<thead>
			<tr>
				<th>Name</th>
				<th></th>
				<th></th>
				<th></th>
			</tr>
		</thead>

		<tbody>
			<% @specializations.each do |specialization| %>
			<tr>
				<td><%= specialization.name %></td>
				<td><%= link_to 'Show', specialization %></td>
				<td><%= link_to 'Edit', edit_specialization_path(specialization) %></td>
				<td><%= link_to 'Destroy', specialization, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
			<% end %>
		</tbody>
	</table>

	<br>

	<%= link_to 'New Specialization', new_specialization_path %>
</div>

app/views/specializations/new.html.erb
<div class="row collapse">
	<h1>New specialization</h1>

	<%= render 'form' %>

	<%= link_to 'Back', specializations_path %>
</div>

app/views/specializations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @specialization.name %>
</p>

<%= link_to 'Edit', edit_specialization_path(@specialization) %> |
<%= link_to 'Back', specializations_path %>

app/views/welcome/index.html.erb
<h1>Project Management System</h1>
<%= link_to "Projects", controller: 'projects'%>